env:
  global:
  - CC_TEST_REPORTER_ID=$CC_TEST_REPORTER_ID
language: ruby
rvm:
- 2.7
- 2.6
- 2.5
- 2.4
- jruby-9.2
before_script:
- make install
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- make test
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
deploy:
  provider: rubygems
  api_key: "$RUBYGEMS_API_KEY"
  gem: ruby_http_client
  on:
    tags: true
    rvm: '2.4'
    skip_cleanup: true
notifications:
  slack:
    if: branch = main
    on_pull_requests: false
    on_success: never
    on_failure: change
    rooms:
      secure: czfOa2uxH9dpRjrMZeGBkuQWLQGP0Qs/RlV3ipg/HJ8Wid9a1m/eNwaD5zVXsdlixu5cvGRJZijF+Nmk1XirKe0rMZySWOygake6W/qNmbZ+6ROqiu/ZBrXlybgHUHTJZn76p9upuIxoAQ+Q4vMHHhLIpMx0qdKeygRwR0a3aHBnM1daZvFIU7rqtI/R8lqOLkcHAm3WjEpP6nmUS939Ln2WOTZPAd971CRKxPGxDnmJzzM9gZkpi9IfyWrgnoaHCLEr1RziofSmikzQFDs2YOPgT3ZIGjJPSR6iNoEzL8xuGNKWmdR/O/gR1uZlqTKk3XS94z38te++02LuJpNYB6Q6n4FqMVAWSFIZ7ItOL7Q/0Z6iSO46yoOsTGbvcY8k18dUVIJgcXpoRV7qojSJr0d0ejsmBU/irK40Z0GhuJzYXwAsj82li4KebnVOat3tu6N9C1QxVtwLT4+d5QKaS+NKWgf+/SSIt1kt4Aa5MED1ksS/MoYjn+izuyCJByjFLmNc1hklitKiRqcla6OxI0tORPv2q5flidqm5JaZbqebb8GFZjC1fWJQi0byMFNWlnJvdEc49HKdfZxXURt5BbdqLC229Jg2vrBDK1GtZbqcEuoaa4O+QXfv/yX/p1MIyK1qfKK0ScHk8ikDm4nxqoSNit1rZ2u2PUzTcCxDRaw=
